### ISSUE TITLE
Client/edit (client/update?)

### ISSUE THREAD

**Issue by natatkinson** [natatkinson/PancakeAppPHPWrapper#2]
Unknown method when running client/edit
DB error when running client/update (tries to update column 'X-API-KEY')

A Database Error Occurred
Error Number: 1054

Unknown column 'X-API-KEY' in 'field list'

UPDATE `pancake_clients` SET `id` = '1', `first_name` = 'fname_edited', `last_name` = 'lastname edited', `email` = 'email@updated.ca', `company` = 'Bigger Stacks', `address` = '1234 Maple Street', `phone` = '888-555-5555', `website` = 'www.website.ca', `X-API-KEY` = 'JtFlTa7yvxdke6hPBI0E4LtKV0ArN3BrdpnTXTkQ' WHERE `id` = '1'

Filename: core/Pancake_Model.php

Line Number: 236

**Comment by joelkallman** [comment]
It is documented as clients/edit but is actually clients/update

As for your DB issue, the problem is that Pancake takes ALL the POST data and attempts to update it. Since X-API-KEY is not a field (obviously) it errors out. 

You can do a couple things:
- Fix the API to only accept values that have corresponding fields
- Pass the X-API-KEY as a custom HTTP header instead of using POST.

Here is an example of how we got around this issue:
https://github.com/Eclarian/PancakeToppings/blob/master/libraries/Pancake_toppings.php#L437

**Comment by natatkinson** [comment]
Working now in Version 4 of pancake
