### ISSUE TITLE
Invoices/show - 500 error

### ISSUE THREAD

**Issue by natatkinson** [natatkinson/PancakeAppPHPWrapper#4]
500 error when running GET on api_1/invoices/show?id=1&X-API-KEY={api_key}

**Comment by jinjie** [comment]
after some troubleshooting, I realized the problem comes from REST_Controller at line 633. hope it helps

**Comment by joelkallman** [comment]
The problem is with the _xss_clean() method within the REST_Controller. You'll see something like the following, but without the **$this->load->library('security')** Add that (line 674) and you should be good to go.

```
    if (CI_VERSION < 2)
    {
        return $bool ? $this->input->xss_clean($val) : $val;
    }
    else
    {
        $this->load->library('security');
        return $bool ? $this->security->xss_clean($val) : $val;
    }
```

Also, I've already reported this in the Beta forum: http://diner.pancakeapp.com/discussion/1185/api-rest_controller-security-not-loaded#latest

**Comment by natatkinson** [comment]
fixed in version 4 of pancake
